stages:
- stage: validate
  dependsOn: build
  displayName: Validate
  jobs:
  - job:
    displayName: Signing Validation
    pool:
      name: Hosted Windows 2019 with VS2019
    steps:
      - task: DownloadBuildArtifacts@0
        displayName: Download Package Artifacts
        inputs:
          buildType: current
          artifactName: 'PackageArtifacts'

      - task: PowerShell@2
        displayName: Validate
        inputs:
          filePath: eng\common\sdk-task.ps1
          arguments: -task SigningValidation -restore -msbuildEngine dotnet
            /p:PackageBasePath='$(Build.ArtifactStagingDirectory)/PackageArtifacts'
            /p:Configuration=Release
        
  - job:
    displayName: SourceLink Validation
    pool:
      name: Hosted Windows 2019 with VS2019
    steps:
      - task: DownloadBuildArtifacts@0
        displayName: Download Blob Artifacts
        inputs:
          buildType: current
          artifactName: 'BlobArtifacts'

      - powershell: 'dotnet tool install sourcelink --tool-path $(Agent.BuildDirectory)/SourceLinkTool --version 3.0.0'
        displayName: 'Install SourceLink CLI'
        
      - task: PowerShell@2
        displayName: Validate
        inputs:
          targetType: filePath
          filePath: '$(Build.SourcesDirectory)/eng/common/publishing/SourceLinkValidation.ps1'
          arguments: '$(Build.ArtifactStagingDirectory)\BlobArtifacts\ $(Agent.BuildDirectory)\Extract\ $(Agent.BuildDirectory)\SourceLinkTool\ false $(Build.Repository.Name) $(Build.SourceVersion)'
        continueOnError: true

- template: \eng\common\templates\release\channels\public-dev-release.yml

- template: \eng\common\templates\release\channels\public-stable-release.yml

- template: \eng\common\templates\release\channels\public-validation-release.yml
