jobs:
- job: setupMaestroVars
  displayName: Setup Maestro Vars
  pool:
    name: Hosted Windows 2019 with VS2019
  steps:
    - task: DownloadBuildArtifacts@0
      displayName: Download Release Configs
      inputs:
        buildType: current
        artifactName: 'ReleaseConfigs'

    - task: powershell@1
      name: setReleaseVars
      displayName: Set Release Configs Vars
      inputs:
        scriptType: inlineScript
        inlineScript: |
          $BarId = Get-Content "$(Build.StagingDirectory)/ReleaseConfigs/BARBuildId.txt" 
          Write-Host "##vso[task.setvariable variable=BARBuildId;isoutput=true]$BarId"
            
          Get-Content "$(Build.StagingDirectory)/ReleaseConfigs/Channels.txt" | ForEach-Object { $Channels += "$_ ," }
          Write-Host "##vso[task.setvariable variable=InitialChannels;isoutput=true]$Channels"
