stages:
- stage: Publish
  dependsOn: validate
  displayName: Developer Channel
  jobs:
  - template: ../setup-maestro-vars.yml

  - job:
    displayName: Symbol Publishing
    dependsOn: setupMaestroVars
    variables:
      - template: ../common-variables.yml
    condition: contains(dependencies.setupMaestroVars.outputs['setReleaseVars.InitialChannels'], variables.PublicDevRelease_Channel_Id)
    pool:
      name: Hosted Windows 2019 with VS2019
    steps:
      - task: DownloadBuildArtifacts@0
        displayName: Download PDB Artifacts
        inputs:
          buildType: current
          artifactName: 'PDBArtifacts'
        continueOnError: true

      - task: DownloadBuildArtifacts@0
        displayName: Download Blob Artifacts
        inputs:
          buildType: current
          artifactName: 'BlobArtifacts'

      - task: PowerShell@2
        displayName: Publish
        inputs:
          filePath: eng\common\sdk-task.ps1
          arguments: -task PublishToSymbolServers -restore -msbuildEngine dotnet
            /p:DotNetSymbolServerTokenMsdl=$(microsoft-symbol-server-pat) 
            /p:DotNetSymbolServerTokenSymWeb=$(symweb-symbol-server-pat) 
            /p:PDBArtifactsDirectory='$(Build.ArtifactStagingDirectory)/PDBArtifacts/'
            /p:BlobBasePath='$(Build.ArtifactStagingDirectory)/BlobArtifacts/'
            /p:Configuration=Release

  - job:
    displayName: Publish to Static Feed
    dependsOn: setupMaestroVars
    condition: contains(dependencies.setupMaestroVars.outputs['setReleaseVars.InitialChannels'], 10)
    variables:
      BARBuildId: $[ dependencies.setupMaestroVars.outputs['setReleaseVars.BARBuildId'] ]
    pool:
      name: Hosted Windows 2019 with VS2019
    steps:
      - task: DownloadBuildArtifacts@0
        displayName: Download Package Artifacts
        inputs:
          buildType: current
          artifactName: 'PackageArtifacts'

      - task: DownloadBuildArtifacts@0
        displayName: Download Blob Artifacts
        inputs:
          buildType: current
          artifactName: 'BlobArtifacts'

      - task: DownloadBuildArtifacts@0
        displayName: Download Asset Manifests
        inputs:
          buildType: current
          artifactName: 'AssetManifests'

      - task: PowerShell@2
        displayName: Publish
        inputs:
          filePath: eng\common\sdk-task.ps1
          arguments: -task PublishToPackageFeed -restore -msbuildEngine dotnet 
            /p:AccountKeyToStaticFeed='$(dotnetfeed-storage-access-key-1)' 
            /p:BARBuildId=$(BARBuildId) 
            /p:MaestroApiEndpoint='$(MaestroApiEndpoint)'
            /p:BuildAssetRegistryToken='$(MaestroApiPassword)' 
            /p:ManifestsBasePath='$(Build.ArtifactStagingDirectory)/AssetManifests/' 
            /p:BlobBasePath='$(Build.ArtifactStagingDirectory)/BlobArtifacts/' 
            /p:PackageBasePath='$(Build.ArtifactStagingDirectory)/PackageArtifacts/' 
            /p:ArtifactsCategory='.NETCore' 
            /p:OverrideAssetsWithSameName=true 
            /p:PassIfExistingItemIdentical=true 
            /p:Configuration=Release 
        continueOnError: true

      - task: PublishBuildArtifacts@1
        displayName: Publish BAR BuildId to VSTS
        inputs:
          PathtoPublish: 'D:\a\1\s\artifacts\log\Debug\PublishToPackageFeed.binlog'
          PublishLocation: Container
          ArtifactName: ReleaseConfigs
        condition: always()
        

- stage: PublishValidation
  displayName: Publish Validation
  jobs:
  - template: ../setup-maestro-vars.yml

  - job:
    displayName: Symbol Availability
    dependsOn: setupMaestroVars
    variables:
      - template: ../common-variables.yml
    condition: contains(dependencies.setupMaestroVars.outputs['setReleaseVars.InitialChannels'], 10)
    pool:
      name: Hosted Windows 2019 with VS2019
    steps:
      - task: DownloadBuildArtifacts@0
        displayName: Download Package Artifacts
        inputs:
          buildType: current
          artifactName: 'PackageArtifacts'

      - task: powershell@1
        displayName:  Install DotNet Symbol
        inputs:
          scriptType: inlineScript
          inlineScript: |
            dotnet tool install dotnet-symbol --tool-path $(Agent.BuildDirectory)/SymbolTool --version $(SymbolToolVersion) --add-source https://api.nuget.org/v3/index.json
        
      - task: PowerShell@2
        displayName: Check Symbol Availability
        inputs:
          targetType: filePath
          filePath: '$(Build.SourcesDirectory)/eng/common/publishing/CheckSymbols.ps1'
          arguments: -InputPath $(Build.ArtifactStagingDirectory)\PackageArtifacts\ -ExtractPath $(Agent.BuildDirectory)\Temp\ -SymbolToolPath $(Agent.BuildDirectory)\SymbolTool\
        continueOnError: true

  - job:
    displayName: Gather Drop
    dependsOn: setupMaestroVars
    condition: contains(dependencies.setupMaestroVars.outputs['setReleaseVars.InitialChannels'], 10)
    variables:
      BARBuildId: $[ dependencies.setupMaestroVars.outputs['setReleaseVars.BARBuildId'] ]
    pool:
      name: Hosted Windows 2019 with VS2019
    steps:
      - task: PowerShell@2
        displayName: Setup Darc CLI
        inputs:
          targetType: filePath
          filePath: '$(Build.SourcesDirectory)/eng/common/darc-init.ps1'

      - powershell: 'darc gather-drop --non-shipping --continue-on-error --id $(BARBuildId) --output-dir $(Agent.BuildDirectory)/Temp/Drop/ --bar-uri $(MaestroApiEndpoint) --password $(MaestroApiPassword)'
        displayName: Run Darc gather-drop
        continueOnError: true

  - template: ../promote-build.yml
    parameters:
      ChannelId: 10
